version: '1'

services:
  avian_frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "9988:3000"
    environment:
      - NODE_ENV=development